### ISSUE TITLE
ImportError: No module named 'pyric'  - when running GNU Radio Controller 

### ISSUE THREAD

**Issue by diarmuidcire** [wishful-project/examples#3]
When running gnu radio code I get the follow error
ImportError: No module named 'pyric'

Its missing from the /home/nodeuser/dev/lib/python3.5  

installed by going into the following directory and installing 
cd /home/nodeuser/dev/bin

(dev) nodeuser@experiment-unit:~/dev/bin$ ./pip install pyric

(dev) nodeuser@experiment-unit:~/examples/gnuradio$ ./wishful_simple_controller --config ./controller_config.yaml 
Traceback (most recent call last):
  File "./wishful_simple_controller", line 11, in <module>
    import wishful_module_gnuradio
  File "/home/nodeuser/dev/lib/python3.5/site-packages/wishful_module_gnuradio/__init__.py", line 3, in <module>
    from .wifi_gnuradio import *
  File "/home/nodeuser/dev/lib/python3.5/site-packages/wishful_module_gnuradio/wifi_gnuradio.py", line 5, in <module>
    import pyric.utils.channels as channels
ImportError: No module named 'pyric'

**Comment by mchwalisz** [comment]
Can you confirm that you have `PyRIC` installed? How did you setup the whole environment?

Please, show what do you have installed in the environment by running:

```
pip freeze
```

Also, please format the messages so that they are readable. It is extremely hard to help if it is not possible to read what's happening.
